[platformio]
default_envs = esp32s3
src_dir = .
extra_configs = ../platformio.inc

[gfxlib]
lib_deps =
    U8g2_for_Adafruit_GFX

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_upload.flash_size = 8MB
board_build.partitions = huge_app.csv
lib_ldf_mode = deep+
lib_extra_dirs = ../..
lib_deps =
    ArduinoJson
    Wire
    HTTPClient
    WiFiClientSecure
    adafruit/Adafruit BusIO
    adafruit/Adafruit GFX Library
    U8g2_for_Adafruit_GFX

[env:esp32s3_static]
extends = env:esp32s3
build_flags =
    -DCROWPANEL_STATIC_PREVIEW=1
